# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Sparkz400.Relayweft
PackageVersion: 0.3.0
InstallerType: portable
Commands:
  - rw
ReleaseDate: 2026-10-05
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/sparkz400/relayweft/releases/download/v0.3.0/rw-windows-amd64.exe
    InstallerSha256: a8c0d80702f0ec05f01ab67eb6e07fd1b578677ced41bca0e5fb7a481f5c880b
  - Architecture: arm64
    InstallerUrl: https://github.com/sparkz400/relayweft/releases/download/v0.3.0/rw-windows-arm64.exe
    InstallerSha256: 654b2b62fbfa3f0ef57c299483ed3791096670c0ce553947b91e7bcd079d495f
ManifestType: installer
ManifestVersion: 1.6.0
